export interface ListItemData {
  [key: string]: string | number;
}

export const listOne: ListItemData[] = [
  { id: 1, title: 'Title 1' },
  { id: 2, title: 'Title 2' },
  { id: 3, title: 'Title 3' },
];

export const listTwo: ListItemData[] = [
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
  { name: 'Name 1', description: 'Description 1' },
  { name: 'Name 2', description: 'Description 2', link: 'google.com' },
  { name: 'Name 3', description: 'Description 3' },
  { name: 'Name 4', description: 'Description 1' },
  { name: 'Name 5', description: 'Description 2', link: 'google.com' },
  { name: 'Name 6', description: 'Description 3' },
];
